name: .NET Core CI

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET Core 8.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install dependencies
      run: dotnet restore

    - name: Publish
      run: dotnet publish ./src/AsepriteToolkit/ -o ./artifacts --runtime win-x64 -c Release /p:DebugType=None /p:DebugSymbols=false

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: artifacts
        path: ./artifacts/
